version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: crud_user
      POSTGRES_PASSWORD: crud_pass
      POSTGRES_DB: crud_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crud_user -d crud_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  # PostgreSQL untuk testing (DB terpisah)
  db_test:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: crud_user
      POSTGRES_PASSWORD: crud_pass
      POSTGRES_DB: crud_test_db
    ports:
      - "5433:5432"

volumes:
  pgdata:
