#!/usr/bin/env bash
# ============================================================
# task-dispatcher.sh — Dispatch tasks ke OMP agents dengan
#   - Usage limit check + auto-fallback
#   - Context guard (auto-compact)
#   - Append-only WORK_CONTRACT documentation
#   - Memory integration (retain via hindsight)
#   - Wait for completion + validate output
# ============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OMP_BIN="${OMP_BIN:-/home/efsatu/.bun/bin/omp}"
OMP_PATH_ENV="PATH=/home/efsatu/.bun/bin:/home/efsatu/.local/bin:/home/efsatu/.nvm/versions/node/v24.14.0/bin:/usr/local/bin:/usr/bin:/bin"
HERDR_BIN="${HERDR_BIN:-/home/efsatu/.local/bin/herdr}"
CONTRACT_FILE="$SCRIPT_DIR/WORK_CONTRACT.md"
STATE_DIR="$SCRIPT_DIR/.state"
USAGE_THRESHOLD_STOP=85
POLL_INTERVAL=8       # seconds between status checks
POLL_TIMEOUT=300      # max seconds to wait for agent response
CONTEXT_COMPACT_KB=500  # compact if session > this size (KB)
MAIN_AGENT_PROVIDER="anthropic"  # provider used by main agent — forbidden for worker spawn

mkdir -p "$STATE_DIR"

# ---- Logging helpers ----
ts()  { date -u '+%Y-%m-%dT%H:%M:%SZ'; }
log() { echo "[$(ts)] $*" >&2; }

contract_append() {
  local type="$1"; shift
  printf "| %-22s | %-12s | %s |\n" "$(ts)" "$type" "$*" >> "$CONTRACT_FILE"
}

init_contract() {
  if [[ ! -f "$CONTRACT_FILE" ]]; then
    cat > "$CONTRACT_FILE" <<EOF
# WORK CONTRACT — AI Agent Orchestration Log
> Append-only. Each row is an immutable event record.
> Generated by task-dispatcher.sh

| timestamp            | type         | detail |
|----------------------|--------------|--------|
EOF
    log "Contract initialized at $CONTRACT_FILE"
  fi
}

# ---- Usage check ----
get_usage_status() {
  "$SCRIPT_DIR/usage-monitor.sh" --json 2>/dev/null
}

provider_ok() {
  local model="$1"
  local usage_json
  usage_json=$(get_usage_status)

  python3 - "$model" "$usage_json" "$USAGE_THRESHOLD_STOP" <<'PYEOF'
import sys, json
model = sys.argv[1]
data  = json.loads(sys.argv[2])
STOP  = float(sys.argv[3])

if "antigravity" in model:
    for acc in data["providers"].get("google-antigravity", {}).get("accounts", []):
        weekly_blocked = any(
            "Weekly" in k and "Google" in k and v["used_pct"] >= 100
            for k, v in acc.get("limits", {}).items()
        )
        if weekly_blocked:
            print("BLOCKED_WEEKLY")
            sys.exit(0)
        for lname, ld in acc.get("limits", {}).items():
            if "Daily" in lname and "Google" in lname:
                pct = ld["used_pct"]
                if pct >= STOP:
                    print(f"OVER_LIMIT:{pct:.1f}%")
                else:
                    print(f"OK:{pct:.1f}%")
                sys.exit(0)
elif "anthropic" in model:
    for acc in data["providers"].get("anthropic", {}).get("accounts", []):
        for lname, ld in acc.get("limits", {}).items():
            if "5 Hour" in lname or "5h" in lname.lower():
                pct = ld["used_pct"]
                if pct >= STOP:
                    print(f"OVER_LIMIT:{pct:.1f}%")
                else:
                    print(f"OK:{pct:.1f}%")
                sys.exit(0)

print("OK:0%")
PYEOF
}

# ---- Provider guard: return 0 (true) if model is forbidden for worker spawn ----
# Forbidden = same provider as MAIN_AGENT_PROVIDER AND not routed via antigravity
is_forbidden_provider() {
  local model="$1"
  # If model contains the main provider string AND does NOT contain "antigravity"
  if [[ "$model" == *"$MAIN_AGENT_PROVIDER"* && "$model" != *"antigravity"* ]]; then
    return 0  # forbidden
  fi
  return 1  # allowed
}

# ---- Task-based model routing ----
route_task() {
  local task_text="$1"
  local lower
  lower=$(echo "$task_text" | tr '[:upper:]' '[:lower:]')

  # Planner keywords → claude-fable-5
  if echo "$lower" | grep -qE '\b(plan|design|architect|analisa|rancang|sistem|adr|evaluasi)\b'; then
    echo "anthropic/claude-fable-5"
    return 0
  fi

  # Worker / execution keywords → gemini-2.5-flash via antigravity
  if echo "$lower" | grep -qE '\b(code|implement|buat|build|fix|debug|test)\b'; then
    echo "google-antigravity/gemini-2.5-flash"
    return 0
  fi
  if echo "$lower" | grep -q "tulis kode"; then
    echo "google-antigravity/gemini-2.5-flash"
    return 0
  fi

  # Default → gemini worker
  echo "google-antigravity/gemini-2.5-flash"
}

# ---- Spawn new agent with given model ----
spawn_agent() {
  local name="$1"
  local model="$2"
  local cwd="${3:-$HOME/my-ai-agents}"
  local split="${4:-right}"

  log "Spawning $name with model=$model"
  "$HERDR_BIN" agent start "$name" \
    --cwd "$cwd" \
    --split "$split" \
    --env "$OMP_PATH_ENV" \
    -- "$OMP_BIN" --model "$model" 2>/dev/null
  sleep 3
  contract_append "SPAWN" "agent=$name model=$model cwd=$cwd"
}

# ---- Check if agent exists and is running ----
agent_exists() {
  local name="$1"
  "$HERDR_BIN" agent get "$name" 2>/dev/null | python3 -c "
import sys,json
try:
    d=json.load(sys.stdin)
    print('yes' if 'agent' in d.get('result',{}) else 'no')
except:
    print('no')
" 2>/dev/null || echo "no"
}

# ---- Check context size ----
check_context() {
  local name="$1"
  local session_path
  session_path=$("$HERDR_BIN" agent get "$name" 2>/dev/null | python3 -c "
import sys,json
d=json.load(sys.stdin)
print(d['result']['agent'].get('agent_session',{}).get('value',''))
" 2>/dev/null || echo "")

  if [[ -n "$session_path" && -f "$session_path" ]]; then
    du -k "$session_path" 2>/dev/null | cut -f1 || echo "0"
  else
    echo "0"
  fi
}

# ---- Wait for agent to finish working ----
wait_for_idle() {
  local name="$1"
  local elapsed=0
  while [[ $elapsed -lt $POLL_TIMEOUT ]]; do
    local screen
    screen=$("$HERDR_BIN" agent read "$name" --source visible --lines 3 2>/dev/null | \
      python3 -c "import sys,json; print(json.load(sys.stdin)['result']['read']['text'])" 2>/dev/null || echo "")
    if ! echo "$screen" | grep -q "Working"; then
      return 0
    fi
    sleep "$POLL_INTERVAL"
    elapsed=$((elapsed + POLL_INTERVAL))
  done
  log "WARNING: $name did not become idle within ${POLL_TIMEOUT}s"
  return 1
}

# ---- Read agent output ----
read_output() {
  local name="$1"
  "$HERDR_BIN" agent read "$name" --source recent-unwrapped --lines 300 2>/dev/null | \
    python3 -c "
import sys,json
try:
    print(json.load(sys.stdin)['result']['read']['text'])
except:
    print('')
" 2>/dev/null || echo ""
}

# ---- Main dispatch function ----
dispatch() {
  local agent_name="$1"
  local task="$2"
  local model="${3:-}"     # if empty, auto-select
  local task_id="${4:-$(date +%s)}"

  init_contract

  # 1. Auto-select model if not given — use route_task() for smart routing
  if [[ -z "$model" ]]; then
    model=$(route_task "$task")
    log "Auto-routed model: $model"
  fi

  # 2. Provider guard — block forbidden providers (main agent's billing pool)
  if is_forbidden_provider "$model"; then
    log "WARNING: model '$model' uses forbidden provider '$MAIN_AGENT_PROVIDER' without antigravity. Overriding..."
    local override_result
    override_result=$("$SCRIPT_DIR/agent-router.sh" best-provider 2>/dev/null)
    local override_model="${override_result%%|*}"
    if [[ "$override_model" == "NONE" ]]; then
      log "❌ NO PROVIDER AVAILABLE after forbidden-provider override. info=$override_result"
      contract_append "BLOCKED" "task_id=$task_id reason=no_provider_after_forbidden_override detail=$override_result"
      echo "BLOCKED:$override_result"
      return 1
    fi
    contract_append "PROVIDER_OVERRIDE" "task_id=$task_id original=$model override=$override_model reason=forbidden_provider"
    log "Provider overridden: $model → $override_model"
    model="$override_model"
  fi

  # 3. Check provider usage
  local usage_status
  usage_status=$(provider_ok "$model")
  if [[ "$usage_status" == OVER_LIMIT* || "$usage_status" == BLOCKED_WEEKLY* ]]; then
    log "⚠️  Provider $model is at limit ($usage_status). Trying fallback..."
    contract_append "LIMIT_HIT" "task_id=$task_id model=$model status=$usage_status"

    # Try fallback
    local fallback_result
    fallback_result=$("$SCRIPT_DIR/agent-router.sh" best-provider 2>/dev/null)
    local fallback_model="${fallback_result%%|*}"
    if [[ "$fallback_model" == "NONE" ]]; then
      log "❌ All providers exhausted. Task $task_id queued."
      contract_append "QUEUED" "task_id=$task_id reason=all_providers_exhausted retry_info=$fallback_result"
      echo "$task" > "$STATE_DIR/queued_${task_id}.task"
      echo "$agent_name" > "$STATE_DIR/queued_${task_id}.agent"
      return 1
    fi
    model="$fallback_model"
    log "Falling back to: $model"
    contract_append "FALLBACK" "task_id=$task_id new_model=$model"
  fi

  # 4. Check/spawn agent
  if [[ "$(agent_exists "$agent_name")" == "no" ]]; then
    log "Agent $agent_name not found. Spawning..."
    spawn_agent "$agent_name" "$model"
    sleep 4
  fi

  # 5. Check context size → compact if needed
  local ctx_kb
  ctx_kb=$(check_context "$agent_name")
  if [[ "$ctx_kb" -gt "$CONTEXT_COMPACT_KB" ]]; then
    log "📦 Context at ${ctx_kb}KB for $agent_name — triggering /compact"
    "$SCRIPT_DIR/agent-router.sh" compact "$agent_name" 2>/dev/null
    sleep 5
    contract_append "COMPACT" "agent=$agent_name session_kb=$ctx_kb"
  fi

  # 6. Send task
  log "📤 Dispatching task[$task_id] to $agent_name: ${task:0:80}..."
  "$HERDR_BIN" agent send "$agent_name" "$task" 2>/dev/null
  contract_append "DISPATCH" "task_id=$task_id agent=$agent_name model=$model task=${task:0:120}"

  # 7. Wait for completion
  log "⏳ Waiting for $agent_name to complete..."
  if wait_for_idle "$agent_name"; then
    local output
    output=$(read_output "$agent_name")
    local out_lines
    out_lines=$(echo "$output" | wc -l)
    contract_append "COMPLETE" "task_id=$task_id agent=$agent_name output_lines=$out_lines"
    log "✅ Task $task_id complete. Output: $out_lines lines"
    echo "$output"
  else
    contract_append "TIMEOUT" "task_id=$task_id agent=$agent_name elapsed=${POLL_TIMEOUT}s"
    log "⚠️  Task $task_id timed out"
    return 1
  fi
}

# ---- Set Goal on agent ----
set_goal() {
  local agent_name="$1"
  local goal="$2"
  log "🎯 Setting goal on $agent_name: ${goal:0:80}"
  "$HERDR_BIN" agent send "$agent_name" "/goal $goal" 2>/dev/null
  contract_append "GOAL_SET" "agent=$agent_name goal=${goal:0:120}"
}

# ---- Set Loop on agent ----
set_loop() {
  local agent_name="$1"
  local interval="${2:-60}"
  local task="${3:-}"
  log "🔁 Setting loop on $agent_name (interval=${interval}m)"
  if [[ -n "$task" ]]; then
    "$HERDR_BIN" agent send "$agent_name" "/loop $task" 2>/dev/null
  else
    "$HERDR_BIN" agent send "$agent_name" "/loop" 2>/dev/null
  fi
  contract_append "LOOP_SET" "agent=$agent_name interval=${interval}m task=${task:0:80}"
}

# ---- CLI entry point ----
case "${1:-help}" in
  dispatch)
    dispatch "${2:?}" "${3:?}" "${4:-}" "${5:-}"
    ;;
  set-goal)
    set_goal "${2:?}" "${3:?}"
    ;;
  set-loop)
    set_loop "${2:?}" "${3:-60}" "${4:-}"
    ;;
  spawn)
    spawn_agent "${2:?}" "${3:?}" "${4:-$HOME/my-ai-agents}" "${5:-right}"
    ;;
  route)
    # Print recommended model for a task text
    route_task "${2:?need task text}"
    ;;
  help|*)
    echo "Usage: task-dispatcher.sh <command>"
    echo "  dispatch <agent> <task> [model] [task_id]"
    echo "  set-goal <agent> <goal text>"
    echo "  set-loop <agent> [interval_min] [task text]"
    echo "  spawn <agent> <model> [cwd] [split]"
    echo "  route <task text>  — print recommended model for task"
    ;;
esac
